# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CommWithReducer_pb2 as CommWithReducer__pb2


class CommWithReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connectToReducer = channel.unary_unary(
                '/CommWithReducer/connectToReducer',
                request_serializer=CommWithReducer__pb2.ReducerRequest.SerializeToString,
                response_deserializer=CommWithReducer__pb2.ReducerResponse.FromString,
                )


class CommWithReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connectToReducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommWithReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connectToReducer': grpc.unary_unary_rpc_method_handler(
                    servicer.connectToReducer,
                    request_deserializer=CommWithReducer__pb2.ReducerRequest.FromString,
                    response_serializer=CommWithReducer__pb2.ReducerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommWithReducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommWithReducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connectToReducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommWithReducer/connectToReducer',
            CommWithReducer__pb2.ReducerRequest.SerializeToString,
            CommWithReducer__pb2.ReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
