# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithReducer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43ommWithReducer.proto\"\xbd\x01\n\x0eReducerRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\x34\n\rtypeOfRequest\x18\x02 \x01(\x0e\x32\x1d.ReducerRequest.TypeOfRequest\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x0f\n\x07mappers\x18\x04 \x01(\x05\"B\n\rTypeOfRequest\x12\r\n\tWordCount\x10\x00\x12\x11\n\rInvertedIndex\x10\x01\x12\x0f\n\x0bNaturalJoin\x10\x02\"!\n\x0fReducerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2J\n\x0f\x43ommWithReducer\x12\x37\n\x10\x63onnectToReducer\x12\x0f.ReducerRequest\x1a\x10.ReducerResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithReducer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDUCERREQUEST._serialized_start=26
  _REDUCERREQUEST._serialized_end=215
  _REDUCERREQUEST_TYPEOFREQUEST._serialized_start=149
  _REDUCERREQUEST_TYPEOFREQUEST._serialized_end=215
  _REDUCERRESPONSE._serialized_start=217
  _REDUCERRESPONSE._serialized_end=250
  _COMMWITHREDUCER._serialized_start=252
  _COMMWITHREDUCER._serialized_end=326
# @@protoc_insertion_point(module_scope)
