# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CommWithMapper_pb2 as CommWithMapper__pb2


class CommWithMapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connectToMapper = channel.unary_unary(
                '/CommWithMapper/connectToMapper',
                request_serializer=CommWithMapper__pb2.MappingRequest.SerializeToString,
                response_deserializer=CommWithMapper__pb2.Response.FromString,
                )


class CommWithMapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connectToMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommWithMapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connectToMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.connectToMapper,
                    request_deserializer=CommWithMapper__pb2.MappingRequest.FromString,
                    response_serializer=CommWithMapper__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommWithMapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommWithMapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connectToMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommWithMapper/connectToMapper',
            CommWithMapper__pb2.MappingRequest.SerializeToString,
            CommWithMapper__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
