# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CommWithMaster_pb2 as CommWithMaster__pb2


class CommWithMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeChoice = channel.unary_unary(
                '/CommWithMaster/MakeChoice',
                request_serializer=CommWithMaster__pb2.RegisterRequest.SerializeToString,
                response_deserializer=CommWithMaster__pb2.RegisterResponse.FromString,
                )


class CommWithMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeChoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommWithMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeChoice': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeChoice,
                    request_deserializer=CommWithMaster__pb2.RegisterRequest.FromString,
                    response_serializer=CommWithMaster__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommWithMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommWithMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeChoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommWithMaster/MakeChoice',
            CommWithMaster__pb2.RegisterRequest.SerializeToString,
            CommWithMaster__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
